# Resources settings
source:      .
layouts:     ./_layouts
timezone:    +0800
lang: zh-CN
gems: ['jekyll-paginate', 'jekyll-multiple-languages']
languages: ['cn', 'en']
language_default: 'en'

# Site settings
name: Mr Wang
subname: 一个热爱折腾、不肯休息的业余程序员！
email: 1806842229@qq.com
author: Deven Wang
url: http://blog.deven.win

github: https://github.com/DevenWang
baseurl: ""
description: 此博客模板由Joytou通过Bootstrap创建
about: 

future: true
show_drafts: nil
lsi: true
published: false
safe: false
permalink: /:year/:month/:day/:title/
paginate: 2
markdown: kramdown
excerpt_separator: '<!-- more -->'

exclude: ['README.md']

github_username: DevenWang
owner_name: Deven Wang

# Keywords
keywords:
        - "github"
        - "blog"
        - "博客"
        - "个人博客"
        - "后台开发"
        
#Others
BaiduSiteVerification: 
